### ISSUE TITLE
Ability to specify multiple cassandra nodes

### ISSUE THREAD

**Issue by julienmoumne** [Galeria-Kaufhof/pillar#26]
`cassandra-seed-address: ["node1","node2","node3"]`

returns

`cassandra-seed-address has type LIST rather than STRING`

I tried using comas : `Failed to add contact point: node1, node2, node3`

**Comment by el-dom** [comment]
Because the config entry gets loaded as a String (see https://github.com/Galeria-Kaufhof/pillar/blob/master/src/main/scala/de/kaufhof/pillar/config/ConnectionConfiguration.scala#L18), setting it as a List won't work. 
The Plugin currently only expects one contact point (see https://github.com/Galeria-Kaufhof/pillar/blob/master/src/main/scala/de/kaufhof/pillar/cli/App.scala#L74)

If you need multiple contact points, that should be easy to enhance and we'll gladly accept a PR for this.

**Comment by el-dom** [comment]
Provided by @grvpuri via https://github.com/Galeria-Kaufhof/pillar/pull/28
